<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>student_test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ff739b8f-03ba-499b-aa45-e20f236e1bb9</testSuiteGuid>
   <testCaseLink>
      <guid>cfebbb67-abb1-4030-881d-752ea0f7dee5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/student_login_success</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>669c9027-b838-428e-a175-cc3451190596</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/bell_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1b3827dc-a08c-402f-bc0c-62d97a5f44c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/reminder_view</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5340932f-1fa0-4da1-8cd0-e6f59fb576ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>977104f9-052d-444e-9256-08ef1d5b020f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f5af195-02f2-430f-aad0-ae3ad69ea05a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/reminder_view_all</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b772f4f8-8846-44bd-b5bc-b4d35b884bb8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/delete_reminder_all</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8e7f8746-36a9-4e58-b76e-6ea46b6324ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact/Student/student_get_teacher_mobile_contact</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>38922aec-f8e1-4bfb-b30c-8b2f045ad22b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Carousel/carousel</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9b2882f0-9a06-45ad-89de-eedbc0b4cc73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Training/student_view_class_training_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>268a3fd4-9194-4734-ba57-516a562b625e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Notice/student_new_one_notice</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a29e86d9-3f45-4711-954c-ed9417c26161</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Notice/student_search_notice_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc2f7f66-e6c6-42b4-b262-e8ff441c428c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>409e8a78-5720-4054-9f37-c4c4f49bf986</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c70c8931-1c19-4275-bf48-c2a7a674b87f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/student_album_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92f1a30e-ce4b-4edd-ba74-77a4f9085a93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2da7b725-02f6-48fb-86c7-f83903baf40e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>437edf87-0827-4b97-bfd3-abdda5482953</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/student_album_picture_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>903d47f1-8712-4ba8-835d-aa62855064dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23c4dfab-18e0-49ce-ae20-f073bf1f4e96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>805956ee-2b93-43ca-84db-6379fbef59dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/student_dynamic_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05941357-5fb1-4def-a08b-a3fe0ffae73e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6110e683-9616-4056-a15b-4a53b0452689</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0706cf29-b57a-4d99-84f4-03cef75c214d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>058b8397-5d27-4d1e-bb62-2b3b6435650f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35a65bc6-98db-4e4b-b3c5-f5519445080c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/student_publish_dynamic_text</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0f6a9f69-98ee-46af-b1ca-6238a29e1028</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/student_publish_dynamic_text_and_picture</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0275473a-0c1c-409b-be9c-2597adc41259</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/student_dynamic_comment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dde2e2c-80ce-4dba-88b5-9e18cc84f826</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a4ee714-d223-47f0-aa08-7d7f1171d535</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ccb104e2-4abf-47f5-8acf-db5a00456fdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/student_dynamic_detele_comment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41591dff-20d9-492a-8c2d-a90a87f7391d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e172dc0-51df-4a28-bc9b-a25b0ca66a6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85c0bc8a-9fd1-4536-93a0-20cb56e11c00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/student_dynamic_like_and_unlike</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d635bf88-34ce-4f89-9a30-866b541c70a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9eff4d4-e418-42e3-a1cf-60a92b1af0a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16f5a737-af3a-445e-984a-e9a6297c520d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/personal_dynamic_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fcc93fe-afac-4a60-b994-1fdb594085b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6ecec67-84ea-473d-89b5-fb7c6fecf7f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07427928-0d0c-4f84-95d9-40b0581eebdc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/search_my_join_vote_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f19eedd1-6130-42a1-a2fb-d60e062a2f78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e58c8094-d469-4619-aa16-598864ba215c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ece5c100-32f7-40c9-a485-fbab063f306c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/vote_detail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98d1ec27-d9df-406e-b442-3a2448ac794a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9b64303-36f2-43d9-817b-a80242e71434</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af804719-0472-47de-9d9d-18cd18b48549</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/voting_detail_and_vote</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e763d2e-093c-4230-a5c4-3fe5ab2e31d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d595f8d2-75bc-42a6-a7d9-919347bc6763</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56fdfdf4-125f-46b9-b893-35b9fb0f9e51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/my_received_notification_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdefbcd2-c64a-4109-8eb3-4fc2eaf429da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6f92558-b4f8-4e3f-a3b8-b39c04996fcc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5311310-132d-4726-bad5-d9edfc409866</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/notification_details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79061151-09c5-442b-ad18-1dc09ae78a2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ef4055-e140-41e5-b2a1-5762a8c03bd4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b78d156-8a0a-4cc0-90ef-68ce06dccdd9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Course Schedule/student_class_course_schedule</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7c6327d2-e696-4000-ac4a-6fa9752b4e19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Live/live</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>29eea507-a548-47b3-aebb-312630da08d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Interactive Course/Interactive_course_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0bd16e6d-647c-4f0e-a6d3-277d1cc35ee9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Menu/menu</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d22a318a-9a67-47e5-8691-78c5c9cb957d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Read Aloud/read_aloud_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d7260a8-6f65-4fed-910d-5677418cedef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f25ca1c3-3a4a-43dd-b65e-e3e0233d648c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33074eb3-018b-40bb-9b2e-3321ecf22c60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Micro Lesson/student_micro_lesson_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b122b3ba-3c49-439b-86e5-255c34b7ae10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef0219ac-ea27-42db-800a-3a437edef8fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6d43f42-3a57-4614-9588-94e0aa4906b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Micro Lesson/student_micro_lesson_list_search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a69caefe-bd16-4ff0-91dd-8aefaddbfba5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c27e918-f943-4f64-88af-c7be1c67e809</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>998168fb-8ee1-4e03-a588-5fc134826d4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a2f9f7b-0409-40e3-9c9b-852bb0ca0e7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Children/history_msg</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4002d24-9a24-46f3-867e-38f0358a4754</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46063859-713b-47cd-a9b1-f96502ae4226</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dad4683e-5e98-4161-b32d-93ff580103d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Children/parent_new_msg_and_send_chat_msg</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8ddd6b53-1f6d-4c3f-a50e-b7ee2780cb00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Teacher/chat_history_latest_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41509884-1ee9-4bb1-8b3a-f346aa4b1168</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae7b0709-2b6e-49dc-b090-0f4774ef21a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Teacher/send_chat_message</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9e2639d2-24fa-4aed-af94-c64b3081e10c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Teacher/send_chat_file</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b0529261-1e29-4b1c-a889-b47c6c2c8622</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Leave/student_leave_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08596cef-001e-486a-83dc-6e054f554d26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>269784e9-749a-49c8-a5ef-20faacb60b4a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7bc429de-e661-486b-a4f0-cfa8529d2e97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Leave/student_leave_text</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12470417-cbd7-4a52-9046-04581486b04e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95b56152-c60f-43f5-9a41-97dd684ebbec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2569cc45-6790-448a-a62c-bdbd43d40a88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Leave/student_leave_text_and_picture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>beb5b8cf-d592-425c-b2dc-686ca861b6fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70f9dd04-7c02-4b7b-b34d-77e61f6a451e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8488c5df-2451-4682-a9a4-8da25dbc6f9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Leave/student_withdraw_leave</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3202da31-4b1b-4a37-8858-333a33ff6eb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1983711d-57de-4460-8299-2332f92a1077</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>daec2a2f-730f-4dc2-8b84-806100a38e6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Attendance/attendance_record_student_detail</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>70141ca7-98d1-4bf6-bc63-bdb6cfe39b7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Attendance/month_simple_statics_about_student</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4c2697cc-a1ed-46c2-a608-eee8fbd6e8bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Achievement/student_achievement_list_and_detail</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>49201fea-d87b-44d6-a620-fcc4a51579ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Homework/student_homework_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ae828eb-fffb-4dad-a8c9-5ba6a39081fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5df2c190-86ac-4226-8f0b-9529649ee508</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>056690d7-46dd-46d7-88c6-7e6dbb42e849</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Homework/student_homework_time_filter_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>101eef70-fc17-4cb7-a63b-ac228fcbf912</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1cca661-b626-4a46-8b64-ad1959ec3050</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3dae42d4-8696-41e3-9b6a-3f38bbe66b4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Homework/student_homework_course_filter_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3cd41ef-a622-470e-8cf0-ee299704a33c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de9fd71c-1980-4521-9e70-5ec2963476f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e03e61a6-8b3e-4ec4-a3de-d4f4fe8c5de5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f431988-6bf0-4a64-b39d-b098ff2142f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Homework/student_homework_time_and_course_filter_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa39dab4-441a-441b-9bb8-d8132d954fca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecc3b50e-2186-4cc0-aa9f-8ea6aa1c708e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96de490e-cc33-4342-8427-15c88034855b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
