<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>student_test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ff739b8f-03ba-499b-aa45-e20f236e1bb9</testSuiteGuid>
   <testCaseLink>
      <guid>cfebbb67-abb1-4030-881d-752ea0f7dee5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/student_login_success</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>669c9027-b838-428e-a175-cc3451190596</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/bell_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1b3827dc-a08c-402f-bc0c-62d97a5f44c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/reminder_view</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5340932f-1fa0-4da1-8cd0-e6f59fb576ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>977104f9-052d-444e-9256-08ef1d5b020f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f5af195-02f2-430f-aad0-ae3ad69ea05a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/reminder_view_all</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b772f4f8-8846-44bd-b5bc-b4d35b884bb8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/delete_reminder_all</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8e7f8746-36a9-4e58-b76e-6ea46b6324ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact/Student/student_get_teacher_mobile_contact</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>38922aec-f8e1-4bfb-b30c-8b2f045ad22b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Carousel/carousel</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9b2882f0-9a06-45ad-89de-eedbc0b4cc73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Training/student_view_class_training_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>268a3fd4-9194-4734-ba57-516a562b625e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Notice/student_new_one_notice</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a29e86d9-3f45-4711-954c-ed9417c26161</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Notice/student_search_notice_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc2f7f66-e6c6-42b4-b262-e8ff441c428c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>409e8a78-5720-4054-9f37-c4c4f49bf986</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c70c8931-1c19-4275-bf48-c2a7a674b87f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/student_album_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92f1a30e-ce4b-4edd-ba74-77a4f9085a93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2da7b725-02f6-48fb-86c7-f83903baf40e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>437edf87-0827-4b97-bfd3-abdda5482953</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/student_album_picture_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>903d47f1-8712-4ba8-835d-aa62855064dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23c4dfab-18e0-49ce-ae20-f073bf1f4e96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>805956ee-2b93-43ca-84db-6379fbef59dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/student_dynamic_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05941357-5fb1-4def-a08b-a3fe0ffae73e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6110e683-9616-4056-a15b-4a53b0452689</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0706cf29-b57a-4d99-84f4-03cef75c214d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>058b8397-5d27-4d1e-bb62-2b3b6435650f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35a65bc6-98db-4e4b-b3c5-f5519445080c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/student_publish_dynamic_text</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0f6a9f69-98ee-46af-b1ca-6238a29e1028</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/student_publish_dynamic_text_and_picture</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0275473a-0c1c-409b-be9c-2597adc41259</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/student_dynamic_comment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dde2e2c-80ce-4dba-88b5-9e18cc84f826</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a4ee714-d223-47f0-aa08-7d7f1171d535</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ccb104e2-4abf-47f5-8acf-db5a00456fdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/student_dynamic_detele_comment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41591dff-20d9-492a-8c2d-a90a87f7391d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e172dc0-51df-4a28-bc9b-a25b0ca66a6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85c0bc8a-9fd1-4536-93a0-20cb56e11c00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/student_dynamic_like_and_unlike</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d635bf88-34ce-4f89-9a30-866b541c70a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9eff4d4-e418-42e3-a1cf-60a92b1af0a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16f5a737-af3a-445e-984a-e9a6297c520d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/personal_dynamic_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fcc93fe-afac-4a60-b994-1fdb594085b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6ecec67-84ea-473d-89b5-fb7c6fecf7f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07427928-0d0c-4f84-95d9-40b0581eebdc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/search_my_join_vote_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f19eedd1-6130-42a1-a2fb-d60e062a2f78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e58c8094-d469-4619-aa16-598864ba215c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ece5c100-32f7-40c9-a485-fbab063f306c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/vote_detail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98d1ec27-d9df-406e-b442-3a2448ac794a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9b64303-36f2-43d9-817b-a80242e71434</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af804719-0472-47de-9d9d-18cd18b48549</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/voting_detail_and_vote</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e763d2e-093c-4230-a5c4-3fe5ab2e31d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d595f8d2-75bc-42a6-a7d9-919347bc6763</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56fdfdf4-125f-46b9-b893-35b9fb0f9e51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/my_received_notification_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdefbcd2-c64a-4109-8eb3-4fc2eaf429da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6f92558-b4f8-4e3f-a3b8-b39c04996fcc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5311310-132d-4726-bad5-d9edfc409866</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/notification_details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79061151-09c5-442b-ad18-1dc09ae78a2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ef4055-e140-41e5-b2a1-5762a8c03bd4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b78d156-8a0a-4cc0-90ef-68ce06dccdd9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Course Schedule/student_class_course_schedule</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7c6327d2-e696-4000-ac4a-6fa9752b4e19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Live/live</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>29eea507-a548-47b3-aebb-312630da08d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Interactive Course/Interactive_course_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0bd16e6d-647c-4f0e-a6d3-277d1cc35ee9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Menu/menu</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ecf89bc5-ff9e-41d1-9018-5671eff79eff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Courseware/courseware_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>28bc33ff-5842-4d08-ae52-b57cc459a71e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Courseware/courseware_list_search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b22adc9-bdc3-4526-a0c7-b54d881c2feb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71e287de-c1ca-45c0-b550-042ab98c4da3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73fdf837-718f-439e-a891-9afa4b82d4cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f632adbe-5c9b-4bc6-88d8-d4497680d3f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Courseware/course_and_grade_and_setting</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>13b5cf15-bb96-43cf-a38e-4b1f163e9e34</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Item Bank/item_bank_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35876df7-19e1-4087-9bd4-aceb253b84bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49c3fb66-fa94-4142-8966-1ac8a2576638</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58065820-603f-4287-9177-d3ebb8adc9b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Item Bank/item_bank_list_search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef481ceb-0b96-450a-94af-97be1c45a278</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d8978f4-19e8-4dd1-8ea0-ba1a7356eb34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cdebe51-38d4-468b-a909-7cfdf16d9b42</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d22a318a-9a67-47e5-8691-78c5c9cb957d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Read Aloud/read_aloud_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d7260a8-6f65-4fed-910d-5677418cedef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f25ca1c3-3a4a-43dd-b65e-e3e0233d648c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
