<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>教师用例</description>
   <name>teacher_20200605_180839</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>409853036@qq.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>994047f9-1638-4250-8ff3-6837ac02792f</testSuiteGuid>
   
<testCaseLink>
      <guid>d10533ab-7da6-4c0e-89dc-b604ff7481ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/SMS/sms_sending</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a2b7a6f-8a8a-46a2-9cb0-c88ffe9d35f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18f37f32-5f64-4500-bb16-caa650635753</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8120cfa5-0ab3-49c3-be4d-4e226ea3aed0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a51aee38-ab76-41a0-9e84-36891e2831f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bb5a45e-1c4a-4b30-accf-81d69b917fcf</variableId>
      </variableLink>
   </testCaseLink>
<testCaseLink>
      <guid>4ebc96c1-57a0-469f-9bd0-05fd7458eb0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/history</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
