<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>教师用例</description>
   <name>teacher</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>409853036@qq.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f161985a-3a80-4b52-b511-ac3c17723c5d</testSuiteGuid>
   <testCaseLink>
      <guid>d38c978f-0603-4ddd-aabf-28ca37e219a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/account_empty</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8c7c05be-8594-4b26-a72e-87bcf140d8b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/account_password_error</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e260cfc6-03e5-4446-a50f-5e9fb2fd8179</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/password_empty</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d06cfd50-9aab-4d6d-8a97-a78c0bdb180e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/teacher_login_success</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bc3db53b-a13e-4b7b-80df-7ee9163bdbd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Carousel/carousel</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0e401a1e-5a8a-4508-add6-708417c84026</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Menu/menu</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>207d2fc9-9449-48cb-a53e-0b5104ffe6e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Change City/change_city</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51b394c5-e762-429a-b60d-34ba6309d84c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>defb99e4-c770-42f9-be22-ec529103fc19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/bell_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>de20dd48-ffde-49ec-9921-4c12ad302203</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/reminder_view</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5340932f-1fa0-4da1-8cd0-e6f59fb576ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>977104f9-052d-444e-9256-08ef1d5b020f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b556d180-257d-4b41-8a5b-5bccd0ce1d12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/reminder_view_all</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e69c7c58-48e6-4d1f-8ce5-fbb8c3ad8a53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/delete_reminder_all</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1f52fbae-28b7-4395-a724-0e06aa9b466d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/add_album</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>971fa24b-2496-423d-9c02-f6fa607bd300</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/album_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cf3a9d1-9fde-4551-a5ca-7021396072ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4528ec54-4095-4369-9787-a21f52506d15</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1373e3c1-255d-41b5-9645-5f758c13ea2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/album_picture_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52550a28-8460-4855-bf70-3ffe38765b62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3c163a9-4ac0-47ca-bd1d-f81d89d6ab2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6fcba94f-ff53-48a3-80ab-55199cfdceca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/upload_album_picture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68c5182a-f99d-401a-a0af-0bee26820c9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>059d17c6-567c-4132-9f67-301efda68335</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b5ad4a4-077f-40f5-a8e6-32fdc249f408</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/edit_album_name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bd47fd0-b74a-4b17-a751-8fb39b30b06f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8dc95d1-c779-4a5f-a820-28c806b9e33c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5a3cb45-edb6-4b5b-9301-3b34a91be59e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/detele_album</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed7a6f87-c790-4d38-ac85-d4b21d624f6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28d14cd6-9c80-4171-b607-83ae5cd2021b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f55afec4-c037-43d2-8a52-1641a36fa8e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/delete_album_picture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7d24421-0c3f-4f07-a755-81ee306d1218</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f00effd-4e99-40ad-ad6f-2d62f65a4f56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41307edd-ec7c-4616-b583-681caa518da7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/dynamic_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f313277a-922b-4eaa-985e-d8e17510054a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14117e43-3ad9-4049-ab6a-f3060d481c54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93256a5b-1fa7-4e3f-847a-e9401f0347b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b882a268-8e30-49ff-9b98-78dc8d290871</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ce3a89e-d42b-4c3c-82c2-3fb697faa3ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/personal_dynamic_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fcc93fe-afac-4a60-b994-1fdb594085b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6ecec67-84ea-473d-89b5-fb7c6fecf7f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7233a9c-9c57-4944-b5f8-0ab278d324d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/publish_dynamic_text</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>820d7189-e2c9-469a-8da4-29101e731676</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/publish_dynamic_text_and_picture</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1f2fa7ed-cfa9-4aff-87d2-1d6f768f09e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/dynamic_like_and_unlike</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b114645c-f333-4335-9ccb-4b80dac85991</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7985ddc4-fd08-4551-b0ed-134eae1ca757</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fee47cd6-cc48-4580-afd2-765aa803817d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/dynamic_comment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2301c93a-c3d8-4156-a83b-ca45cea74a45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b60210b7-aad3-4208-8159-38bf8e1f5cf6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9c3e85a-8411-4cd0-87ba-78b4ee7ab196</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/dynamic_detele_comment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14e00238-1ac3-4548-b245-4b6d2e516e39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06c5d0a8-fd9c-45fa-b738-b3c88b56ecf4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1beed6d-1f63-4ac8-988e-81433bdd3c52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/detele_personal_dynamic</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d90acee-b124-498c-93c3-98f8e3b65c73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3065ae16-5390-47b4-81f5-2a995c1cf9a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e82b496d-d2dd-4ade-a230-07c8f08059b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/detele_dynamic</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd4e8a6d-0e3d-4478-be45-d35db525c4f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c3aed22-1a0f-4eb4-8c9a-0fa449eb8dd4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ee8c5d6-d1a1-4460-aa0a-56be875b624e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Training/teacher_view_class_training_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ff6a3bd9-524c-4a53-84ca-5d5bb365d670</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Training/edit_class_training</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>43112f48-5661-4f59-87bc-bbb4d0682ea2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Notice/teacher_new_one_notice</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e53c00ca-8fab-44e5-9cc9-084c85d5615e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Notice/teacher_search_notice_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>151c1e95-a4d7-48c5-8a08-35b90ce3ef3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bb2196f-a7e2-4d09-a22a-d077cdaac1e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4358f95-5f39-46e0-bdde-5fd9d3bb5a89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Notice/add_notice</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ad3b64b0-1764-4b78-b3f0-57d81f5770df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Notice/delete_notice</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a3b0963-27dc-47ae-8ea8-5bbd8dfa8749</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>535c4e8f-8f09-4a4a-a909-33528d5d0849</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f33778e-3330-4932-91bb-3e75a5cc28b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact/Search/search_contact_mobile_name_or_phone_number</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59f3c445-4afe-4616-baf8-4026d76e3575</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>882c4b26-bbf4-4763-a72c-0c6ab70aa1d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact/Student/student_mobile_contact</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9a3e4352-a948-46f4-83af-dde1f229e132</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact/Teacher/teacher_mobile_contact</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d10533ab-7da6-4c0e-89dc-b604ff7481ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/SMS/sms_sending</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a2b7a6f-8a8a-46a2-9cb0-c88ffe9d35f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18f37f32-5f64-4500-bb16-caa650635753</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8120cfa5-0ab3-49c3-be4d-4e226ea3aed0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a51aee38-ab76-41a0-9e84-36891e2831f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bb5a45e-1c4a-4b30-accf-81d69b917fcf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9581b76-fa61-41b3-98fc-a0312caf7b75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/SMS/sms_sent</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dd73d7e6-7e76-4910-9e30-891ec45022a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/SMS/sms_template_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d723136-f56b-48f3-ba9b-9c79f4be1be8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>327b6134-e3c0-457d-ac49-ffe21d6a59d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e6b99aa-cd13-45be-b293-7df27731cb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f53895b-9f41-47c5-a339-a98d6d95fdee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06f193a9-6345-46a2-8a31-b538a9be6157</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/SMS/sms_timed_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0048bdba-df0c-4858-9bc3-768ee4770036</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ff33b3d-2c66-4868-98f2-25adf979022f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80205c56-b80a-4904-8864-c7cd21af60ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/search_my_join_vote_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f19eedd1-6130-42a1-a2fb-d60e062a2f78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e58c8094-d469-4619-aa16-598864ba215c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>383a9819-0e58-4cd9-9ac1-15c93d828a82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/search_my_start_vote_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18020ea8-0395-47bf-ae63-7a04677ce0cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7df64ebb-0af3-43b3-828b-62e6cae3e5c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>014aedad-5241-4053-82e8-a0983289da3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/publish_vote_text</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16dfa357-060e-4c7c-8888-a25ddefae709</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>646928a8-07e3-4b9a-b6ca-a19476069c1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3f549c0-6925-463c-a608-a62a540538bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea016bda-054f-4700-93ff-f44864252502</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d8efe3f-4a2f-4d25-bf4c-9e50e4311462</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa4fc9f4-9f67-41d9-b8b7-04bfd0d280bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8266c48f-c081-4a22-b5f0-22b5c67e65f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>531f7d59-ce69-4910-ad5e-47399a94e329</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79ad915e-a4b1-48b9-9bbb-50d1e5d71581</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/publish_vote_picture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab48df43-0efb-4ed5-9e2e-eae6b47e2ff9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88afd680-5e41-453a-9058-c2f4c3c59786</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae1946e0-e08b-4223-abc5-a1c61c5a2047</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaefe1b9-d6dc-46b8-8cf3-46b431b64977</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7302bf11-7db8-4ea9-ad38-636787ce9c9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a41370ba-4abb-4734-bbc3-0fb25ce14ac0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca996108-4fcf-4e2f-ba03-f96ed9bf3344</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2441e92-9673-4aaf-8d3a-8ab9350890b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a57d8070-b30e-47fe-9afd-826c439ce5e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/vote_detail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98d1ec27-d9df-406e-b442-3a2448ac794a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9b64303-36f2-43d9-817b-a80242e71434</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>728c0703-b871-4597-b6db-c35fb1d8f157</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/voting_detail_and_vote</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e763d2e-093c-4230-a5c4-3fe5ab2e31d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d595f8d2-75bc-42a6-a7d9-919347bc6763</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ac958c2-21c7-416a-804b-d13f78218c49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/vote_detail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98d1ec27-d9df-406e-b442-3a2448ac794a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9b64303-36f2-43d9-817b-a80242e71434</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae29d019-9a74-426f-afeb-06c09df3a94b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/voting_detail_and_vote</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e763d2e-093c-4230-a5c4-3fe5ab2e31d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d595f8d2-75bc-42a6-a7d9-919347bc6763</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa702d40-e6b1-46f4-b7ab-6bb0d8c3c719</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/my_send_notification_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8810ebe1-bac9-4987-b529-498f15d830b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8c01073-d848-4d69-bd51-2f6df18036c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34e24b57-d8e9-4216-a530-711de581fc94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/my_received_notification_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdefbcd2-c64a-4109-8eb3-4fc2eaf429da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6f92558-b4f8-4e3f-a3b8-b39c04996fcc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f19129f0-c1f1-4d08-8e0d-bf165a552a8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/notification_unread</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71497c4f-fec4-4c7e-9612-5b701ece1589</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fabc1a8f-742c-45fe-bd7b-60ebf676a1c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d43f8b71-1c64-4daf-bb6d-93cf633b5eb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/notification_details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79061151-09c5-442b-ad18-1dc09ae78a2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ef4055-e140-41e5-b2a1-5762a8c03bd4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>012fa41b-48a4-4d18-850c-f47be0b810f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/publish_notification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a6dbc3d-73a1-490a-a096-7e3c70c7183a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20f2863a-1a12-42aa-9a55-dad89bae5610</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78a6e8b8-fa3b-4912-8a68-f96494217890</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff5b5b7a-7f05-4331-bbb2-59e23a16fff5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/delete_notification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecc0c540-5c96-471c-b427-2028d355dc87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c025e50-66ec-4d43-9bf4-603425b172d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ebc96c1-57a0-469f-9bd0-05fd7458eb0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/history</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>60ce70a1-f3cb-4011-9a2c-3c2a4467867e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/student_contact</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9487a465-3de6-4855-8787-55845b13e2de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/delete_history_item</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3ad88663-e3d6-4eb9-90b5-5b32d004232c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/search_student_by_name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>850ba6ad-15b0-4214-a7bc-9d727e866e6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>28190dfd-6c38-4ac6-b665-77dbc58ff68d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/chat _record</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>306b65f2-1785-4d60-8aea-6bf97f00839a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>71f7f649-0048-4b81-b98c-c8219384564c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/send_chat_message</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4d47790a-8356-4475-8f01-53bd4bd08c6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/send_chat_file</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6b98617d-51a8-494c-ad3f-c5ebf3baccc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Attendance/attendance_record_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b22e4c9a-a95f-4155-bf5d-09adebecb159</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Attendance/attendance_record_class_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6fdfffa5-92dc-43cd-a838-2759e91c8db1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Attendance/attendance_record_class_detail</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3728f00e-dfec-4af6-a967-aba4cff7e692</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Attendance/view_statictics_by_klass_one_day</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4cb358aa-2367-4f3f-affa-863540a378ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Attendance/month_simple_statics_about_class</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d31c41cf-db22-4e48-9c87-6c3576c78c5b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Leave/approval_pending_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40cee654-3bf3-4c83-bc52-1b1fdea08617</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0d824a0-a89a-4290-8197-8c9d53fa408f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17ece52e-98ed-4ace-8b8a-8c075f308402</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95fb0bf1-882e-4ebb-8ea0-2c9edcd33081</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ced64aa3-c373-4029-9293-3fad9d822772</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Leave/approved_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e6c6463-064c-42aa-a248-205eefac1ce8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2329c3e1-4543-40f2-906e-e0bb63841a4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>427ecea6-20c8-4420-beb6-2e116b97aa7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26e6df48-bdc0-4f7f-bef1-372ac816c776</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa1638e1-91f5-4921-bdf9-d0270753df24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Leave/agree_leave</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc7b0529-8989-4e12-a674-6cf74fe48a1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9525b271-b840-432c-81d5-9fa53fa1ee22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f22a9c2-0c70-4680-80f1-a0659eeba885</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2af20300-4032-4e23-9080-2d3502eef483</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f471cc42-a0ee-4600-84a5-f6fe39b630bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Leave/refuse_leave</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c58a9598-a9e3-4f1a-bed8-82226e7d2080</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6aac510-0968-4cca-a773-e57638fced46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>264b0eac-51f2-4a35-a199-bca028d23ca3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51d3e01a-9279-4eb6-ba7a-52a9fe324319</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27ca77e6-2368-4d06-abb9-7cd6953e5473</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Leave/leave_records</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9db147cb-ea66-4007-806f-b0bee17ba85e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e33f7ee-d86e-4c1a-9721-5acdcd2c5663</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f8bf4a4-6eaa-40f8-94a3-4480fb923eab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Leave/leave_records_class</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>993c075d-556e-4442-93a1-92ba2a746279</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d510b67-ad2a-4652-a5bc-2c4a5a6e6eba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd9a8c60-d7cf-4dbc-be1d-902439f2f52a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Brand/binging_brand</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b7ad9c8-1fa8-4c4f-9b09-49961ff400e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf62f890-609e-4d06-9f90-7d18d30e8a72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Brand/is_bound_brand_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f34c00dd-78c2-45d9-be9a-e6f9c2cfcc61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8130aeff-6cc2-4444-8be3-ab58c5830f63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>843f21c2-d058-46f0-9d98-250aa419738d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Brand/not_bound_brand_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62eddfad-69dc-41fe-8562-0ae99dc736ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d75f989-9502-47b1-abc5-8f233a7c2ec8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bb62d03-3603-4102-be41-57c728545789</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Homework/teacher_homewrok_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c605628a-5191-46d6-952e-76fb5ee0e824</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d3c3079-8a08-4bf0-8ae3-6fd06301b8c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc25411d-bd59-4119-a74e-1432823516b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Homework/teacher_homework_time_filter_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dc588aa-0bf7-4448-8df6-0be131aef813</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27a589a4-0bf2-4e8b-8ff3-c32eeca8630d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>efb8e84f-303b-4ea2-b2fd-1ddeab915c8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Homework/publish_homework_text</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a164ea51-1b19-401f-a394-34837ca3da5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>969404b2-1b2d-4d68-aca3-703cb43ec4df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Homework/publish_homework_text_and_picture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f309f70-b1e9-45c6-8b5c-396c6275873a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7defb10-34ad-4614-bebd-eeef594d5054</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Homework/delete_homework</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>196b236c-ebc1-4c96-aa33-01455541df59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51046560-e5f7-4dde-9d50-bf015ab745a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4dd459e9-6e1b-4490-9e63-75fb1c530e99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Course Schedule/class_course_schedule</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d213618f-640f-4de8-a741-8299fbe3a4a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Course Schedule/teacher_teach_course_schedule</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ad587733-54e2-4772-acbd-afcd2f15e750</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Achievement/achievement_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1bfe450d-6008-47f1-aba9-486de28a5713</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Achievement/look_student_achievement_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4cffe64c-9cb8-4e10-bac2-d11de1027753</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Achievement/look_student_achievement_detail</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bd86e7e2-7b76-48b9-ae31-fae32e5d8239</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Interactive Course/Interactive_course_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7588a23a-efee-4ac4-a7f0-e0c2bb0dbf2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Live/live</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8dfc8ae6-3cb0-462f-aeb4-1ffba7fe287c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/New college entrance examination/default_and_search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f336c841-d474-4882-8f11-9d658eea076c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3848c44b-3763-41c6-89ea-6774018ca69c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69ff5c17-8f2f-4d3a-a87d-615c238dd5e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/New college entrance examination/select_require_list_filter</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b4c374-3075-4370-aea1-72e49a5e67c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51fd8d90-661a-4692-a6a8-32fcb5a585be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9e7e4c50-5410-4694-b7c1-dd1a28cf8c87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/New college entrance examination/school_query</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd0aba66-fcca-4fc4-bd6b-610ad236474f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c10befa8-61aa-4f05-8f15-ec3c14af7edc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d1b7432c-0f35-4457-a6bb-344be758e5de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/New college entrance examination/college_entrance_exam_information_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d24ea5be-9351-43ae-92ac-055e022c98d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9e3c9af-c634-4352-852a-80b98500c164</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e0a280a-5a97-46fe-ab49-9dd6cf7b7b95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61720764-dbd0-4979-ab3b-6bd9f1d4eac6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Courseware/course_and_grade_and_setting</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f5bb931f-ab36-40f7-b24f-f366490f3116</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Courseware/courseware_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>674effb4-670b-41a4-8e22-bea3fefe67aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Courseware/courseware_list_search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b22adc9-bdc3-4526-a0c7-b54d881c2feb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71e287de-c1ca-45c0-b550-042ab98c4da3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73fdf837-718f-439e-a891-9afa4b82d4cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82b14546-69ea-40f8-b823-e0a010e48ea9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Item Bank/item_bank_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35876df7-19e1-4087-9bd4-aceb253b84bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49c3fb66-fa94-4142-8966-1ac8a2576638</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6de978e1-e746-483a-9da0-432208464410</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Item Bank/item_bank_list_search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef481ceb-0b96-450a-94af-97be1c45a278</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d8978f4-19e8-4dd1-8ea0-ba1a7356eb34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cdebe51-38d4-468b-a909-7cfdf16d9b42</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e0f85a5-792a-4a7d-82c1-cf4748095b36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Read Aloud/read_aloud_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d7260a8-6f65-4fed-910d-5677418cedef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f25ca1c3-3a4a-43dd-b65e-e3e0233d648c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2523b52c-f2ee-4e50-a57a-d7df2d3cc359</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Micro Lesson/micro_lesson_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eed148ca-3f42-4ebf-b688-61cbf0e834e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b044aa41-91ec-46f0-9513-8ad7f8116299</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27d04da0-bd84-48a2-862e-66cbb0a836fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Resources/Micro Lesson/micro_lesson_list_search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f6f36f0-cafa-4625-a6bd-a9c917f97728</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>897315ec-598c-4d0e-b1c7-09e66a6dbcd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3bee207-25d5-42c5-9275-173173d985e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d861e02-e103-4206-95d2-f4b8e5c50058</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/My/Individual/Teacher/personal_data</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d277e7ae-e885-4124-b8b8-bf59fd966f1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/My/Help Center/help_center_list_and_details</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
