<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>教师用例</description>
   <name>teacher</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>409853036@qq.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f161985a-3a80-4b52-b511-ac3c17723c5d</testSuiteGuid>
   <testCaseLink>
      <guid>d38c978f-0603-4ddd-aabf-28ca37e219a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/account_empty</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8c7c05be-8594-4b26-a72e-87bcf140d8b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/account_password_error</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e260cfc6-03e5-4446-a50f-5e9fb2fd8179</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/password_empty</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d06cfd50-9aab-4d6d-8a97-a78c0bdb180e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/teacher_login_success</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bc3db53b-a13e-4b7b-80df-7ee9163bdbd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Carousel/carousel</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0e401a1e-5a8a-4508-add6-708417c84026</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Menu/menu</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>207d2fc9-9449-48cb-a53e-0b5104ffe6e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Change City/change_city</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51b394c5-e762-429a-b60d-34ba6309d84c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>defb99e4-c770-42f9-be22-ec529103fc19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/bell_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>de20dd48-ffde-49ec-9921-4c12ad302203</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/reminder_view</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5340932f-1fa0-4da1-8cd0-e6f59fb576ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>977104f9-052d-444e-9256-08ef1d5b020f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b556d180-257d-4b41-8a5b-5bccd0ce1d12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/reminder_view_all</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e69c7c58-48e6-4d1f-8ce5-fbb8c3ad8a53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/delete_reminder_all</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1f52fbae-28b7-4395-a724-0e06aa9b466d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/add_album</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>971fa24b-2496-423d-9c02-f6fa607bd300</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/album_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cf3a9d1-9fde-4551-a5ca-7021396072ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4528ec54-4095-4369-9787-a21f52506d15</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1373e3c1-255d-41b5-9645-5f758c13ea2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/album_picture_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52550a28-8460-4855-bf70-3ffe38765b62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3c163a9-4ac0-47ca-bd1d-f81d89d6ab2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6fcba94f-ff53-48a3-80ab-55199cfdceca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/upload_album_picture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68c5182a-f99d-401a-a0af-0bee26820c9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>059d17c6-567c-4132-9f67-301efda68335</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b5ad4a4-077f-40f5-a8e6-32fdc249f408</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/edit_album_name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bd47fd0-b74a-4b17-a751-8fb39b30b06f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8dc95d1-c779-4a5f-a820-28c806b9e33c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5a3cb45-edb6-4b5b-9301-3b34a91be59e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/detele_album</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed7a6f87-c790-4d38-ac85-d4b21d624f6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28d14cd6-9c80-4171-b607-83ae5cd2021b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f55afec4-c037-43d2-8a52-1641a36fa8e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/delete_album_picture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7d24421-0c3f-4f07-a755-81ee306d1218</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f00effd-4e99-40ad-ad6f-2d62f65a4f56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41307edd-ec7c-4616-b583-681caa518da7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/dynamic_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f313277a-922b-4eaa-985e-d8e17510054a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14117e43-3ad9-4049-ab6a-f3060d481c54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93256a5b-1fa7-4e3f-847a-e9401f0347b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b882a268-8e30-49ff-9b98-78dc8d290871</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ce3a89e-d42b-4c3c-82c2-3fb697faa3ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/personal_dynamic_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fcc93fe-afac-4a60-b994-1fdb594085b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6ecec67-84ea-473d-89b5-fb7c6fecf7f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7233a9c-9c57-4944-b5f8-0ab278d324d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/publish_dynamic_text</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>820d7189-e2c9-469a-8da4-29101e731676</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/publish_dynamic_text_and_picture</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1f2fa7ed-cfa9-4aff-87d2-1d6f768f09e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/dynamic_like_and_unlike</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b114645c-f333-4335-9ccb-4b80dac85991</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7985ddc4-fd08-4551-b0ed-134eae1ca757</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fee47cd6-cc48-4580-afd2-765aa803817d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/dynamic_comment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2301c93a-c3d8-4156-a83b-ca45cea74a45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b60210b7-aad3-4208-8159-38bf8e1f5cf6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9c3e85a-8411-4cd0-87ba-78b4ee7ab196</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/dynamic_detele_comment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14e00238-1ac3-4548-b245-4b6d2e516e39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06c5d0a8-fd9c-45fa-b738-b3c88b56ecf4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1beed6d-1f63-4ac8-988e-81433bdd3c52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/detele_personal_dynamic</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d90acee-b124-498c-93c3-98f8e3b65c73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3065ae16-5390-47b4-81f5-2a995c1cf9a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e82b496d-d2dd-4ade-a230-07c8f08059b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Dynamic/detele_dynamic</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd4e8a6d-0e3d-4478-be45-d35db525c4f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c3aed22-1a0f-4eb4-8c9a-0fa449eb8dd4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ee8c5d6-d1a1-4460-aa0a-56be875b624e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Training/view_class_training_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ff6a3bd9-524c-4a53-84ca-5d5bb365d670</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Class Training/edit_class_training</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>43112f48-5661-4f59-87bc-bbb4d0682ea2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Notice/new_one_notice</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e53c00ca-8fab-44e5-9cc9-084c85d5615e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Notice/search_notice_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>151c1e95-a4d7-48c5-8a08-35b90ce3ef3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bb2196f-a7e2-4d09-a22a-d077cdaac1e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4358f95-5f39-46e0-bdde-5fd9d3bb5a89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Notice/add_notice</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ad3b64b0-1764-4b78-b3f0-57d81f5770df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Notice/delete_notice</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a3b0963-27dc-47ae-8ea8-5bbd8dfa8749</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>535c4e8f-8f09-4a4a-a909-33528d5d0849</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f33778e-3330-4932-91bb-3e75a5cc28b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact/Search/search_contact_mobile_name_or_phone_number</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59f3c445-4afe-4616-baf8-4026d76e3575</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>882c4b26-bbf4-4763-a72c-0c6ab70aa1d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact/Student/student_mobile_contact</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9a3e4352-a948-46f4-83af-dde1f229e132</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact/Teacher/teacher_mobile_contact</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d10533ab-7da6-4c0e-89dc-b604ff7481ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/SMS/sms_sending</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a2b7a6f-8a8a-46a2-9cb0-c88ffe9d35f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18f37f32-5f64-4500-bb16-caa650635753</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8120cfa5-0ab3-49c3-be4d-4e226ea3aed0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a51aee38-ab76-41a0-9e84-36891e2831f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bb5a45e-1c4a-4b30-accf-81d69b917fcf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9581b76-fa61-41b3-98fc-a0312caf7b75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/SMS/sms_sent</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dd73d7e6-7e76-4910-9e30-891ec45022a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/SMS/sms_template_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d723136-f56b-48f3-ba9b-9c79f4be1be8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>327b6134-e3c0-457d-ac49-ffe21d6a59d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e6b99aa-cd13-45be-b293-7df27731cb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f53895b-9f41-47c5-a339-a98d6d95fdee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06f193a9-6345-46a2-8a31-b538a9be6157</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/SMS/sms_timed_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0048bdba-df0c-4858-9bc3-768ee4770036</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ff33b3d-2c66-4868-98f2-25adf979022f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80205c56-b80a-4904-8864-c7cd21af60ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/search_my_join_vote_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f19eedd1-6130-42a1-a2fb-d60e062a2f78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e58c8094-d469-4619-aa16-598864ba215c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>383a9819-0e58-4cd9-9ac1-15c93d828a82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/search_my_start_vote_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18020ea8-0395-47bf-ae63-7a04677ce0cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7df64ebb-0af3-43b3-828b-62e6cae3e5c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>014aedad-5241-4053-82e8-a0983289da3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/publish_vote_text</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16dfa357-060e-4c7c-8888-a25ddefae709</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>646928a8-07e3-4b9a-b6ca-a19476069c1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3f549c0-6925-463c-a608-a62a540538bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea016bda-054f-4700-93ff-f44864252502</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d8efe3f-4a2f-4d25-bf4c-9e50e4311462</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa4fc9f4-9f67-41d9-b8b7-04bfd0d280bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8266c48f-c081-4a22-b5f0-22b5c67e65f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>531f7d59-ce69-4910-ad5e-47399a94e329</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79ad915e-a4b1-48b9-9bbb-50d1e5d71581</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/publish_vote_picture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab48df43-0efb-4ed5-9e2e-eae6b47e2ff9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88afd680-5e41-453a-9058-c2f4c3c59786</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae1946e0-e08b-4223-abc5-a1c61c5a2047</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaefe1b9-d6dc-46b8-8cf3-46b431b64977</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7302bf11-7db8-4ea9-ad38-636787ce9c9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a41370ba-4abb-4734-bbc3-0fb25ce14ac0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca996108-4fcf-4e2f-ba03-f96ed9bf3344</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2441e92-9673-4aaf-8d3a-8ab9350890b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a57d8070-b30e-47fe-9afd-826c439ce5e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/vote_detail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98d1ec27-d9df-406e-b442-3a2448ac794a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9b64303-36f2-43d9-817b-a80242e71434</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>728c0703-b871-4597-b6db-c35fb1d8f157</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/voting_detail_and_vote</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e763d2e-093c-4230-a5c4-3fe5ab2e31d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d595f8d2-75bc-42a6-a7d9-919347bc6763</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ac958c2-21c7-416a-804b-d13f78218c49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/vote_detail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98d1ec27-d9df-406e-b442-3a2448ac794a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9b64303-36f2-43d9-817b-a80242e71434</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae29d019-9a74-426f-afeb-06c09df3a94b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Vote/voting_detail_and_vote</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e763d2e-093c-4230-a5c4-3fe5ab2e31d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d595f8d2-75bc-42a6-a7d9-919347bc6763</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa702d40-e6b1-46f4-b7ab-6bb0d8c3c719</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/my_send_notification_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8810ebe1-bac9-4987-b529-498f15d830b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8c01073-d848-4d69-bd51-2f6df18036c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34e24b57-d8e9-4216-a530-711de581fc94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/my_received_notification_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdefbcd2-c64a-4109-8eb3-4fc2eaf429da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6f92558-b4f8-4e3f-a3b8-b39c04996fcc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f19129f0-c1f1-4d08-8e0d-bf165a552a8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/notification_unread</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71497c4f-fec4-4c7e-9612-5b701ece1589</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fabc1a8f-742c-45fe-bd7b-60ebf676a1c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d43f8b71-1c64-4daf-bb6d-93cf633b5eb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/notification_details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79061151-09c5-442b-ad18-1dc09ae78a2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ef4055-e140-41e5-b2a1-5762a8c03bd4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>012fa41b-48a4-4d18-850c-f47be0b810f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/publish_notification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a6dbc3d-73a1-490a-a096-7e3c70c7183a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20f2863a-1a12-42aa-9a55-dad89bae5610</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78a6e8b8-fa3b-4912-8a68-f96494217890</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff5b5b7a-7f05-4331-bbb2-59e23a16fff5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Notification/delete_notification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecc0c540-5c96-471c-b427-2028d355dc87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c025e50-66ec-4d43-9bf4-603425b172d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ebc96c1-57a0-469f-9bd0-05fd7458eb0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/history</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>60ce70a1-f3cb-4011-9a2c-3c2a4467867e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/student_contact</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9487a465-3de6-4855-8787-55845b13e2de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/delete_history_item</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3ad88663-e3d6-4eb9-90b5-5b32d004232c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/search_student_by_name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>850ba6ad-15b0-4214-a7bc-9d727e866e6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>28190dfd-6c38-4ac6-b665-77dbc58ff68d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/chat _record</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>306b65f2-1785-4d60-8aea-6bf97f00839a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>71f7f649-0048-4b81-b98c-c8219384564c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/send_chat_message</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4d47790a-8356-4475-8f01-53bd4bd08c6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Contact Parents/send_chat_file</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6b98617d-51a8-494c-ad3f-c5ebf3baccc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Attendance/attendance_record_list</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
