<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>教师用例</description>
   <name>teacher</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>409853036@qq.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f161985a-3a80-4b52-b511-ac3c17723c5d</testSuiteGuid>
   <testCaseLink>
      <guid>d38c978f-0603-4ddd-aabf-28ca37e219a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/account_empty</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8c7c05be-8594-4b26-a72e-87bcf140d8b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/account_password_error</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e260cfc6-03e5-4446-a50f-5e9fb2fd8179</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/password_empty</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d06cfd50-9aab-4d6d-8a97-a78c0bdb180e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Login And Logout/teacher_login_success</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bc3db53b-a13e-4b7b-80df-7ee9163bdbd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Carousel/carousel</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0e401a1e-5a8a-4508-add6-708417c84026</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Menu/menu</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>207d2fc9-9449-48cb-a53e-0b5104ffe6e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Change City/change_city</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51b394c5-e762-429a-b60d-34ba6309d84c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>defb99e4-c770-42f9-be22-ec529103fc19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/bell_list</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>de20dd48-ffde-49ec-9921-4c12ad302203</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/reminder_view</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5340932f-1fa0-4da1-8cd0-e6f59fb576ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>977104f9-052d-444e-9256-08ef1d5b020f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b556d180-257d-4b41-8a5b-5bccd0ce1d12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/reminder_view_all</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e69c7c58-48e6-4d1f-8ce5-fbb8c3ad8a53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Bell/delete_reminder_all</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1f52fbae-28b7-4395-a724-0e06aa9b466d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/add_album</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>971fa24b-2496-423d-9c02-f6fa607bd300</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/album_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cf3a9d1-9fde-4551-a5ca-7021396072ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4528ec54-4095-4369-9787-a21f52506d15</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1373e3c1-255d-41b5-9645-5f758c13ea2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/album_picture_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52550a28-8460-4855-bf70-3ffe38765b62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3c163a9-4ac0-47ca-bd1d-f81d89d6ab2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6fcba94f-ff53-48a3-80ab-55199cfdceca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/upload_album_picture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68c5182a-f99d-401a-a0af-0bee26820c9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>059d17c6-567c-4132-9f67-301efda68335</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b5ad4a4-077f-40f5-a8e6-32fdc249f408</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/edit_album_name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bd47fd0-b74a-4b17-a751-8fb39b30b06f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8dc95d1-c779-4a5f-a820-28c806b9e33c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5a3cb45-edb6-4b5b-9301-3b34a91be59e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/detele_album</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed7a6f87-c790-4d38-ac85-d4b21d624f6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28d14cd6-9c80-4171-b607-83ae5cd2021b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f55afec4-c037-43d2-8a52-1641a36fa8e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Api/Mobile Api/Campus/Class Circle/Album/delete_album_picture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7d24421-0c3f-4f07-a755-81ee306d1218</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f00effd-4e99-40ad-ad6f-2d62f65a4f56</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
