<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>班级圈</description>
   <name>class_circle</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3466a529-5bdb-432f-958b-05815dd65f01</testSuiteGuid>
   <testCaseLink>
      <guid>5b2b63bf-257c-4472-858f-8015c69b538d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Bottom Navigation/Campus/Interactive Management/Class Circle/ui_element</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>42e2740e-2436-43f1-842e-8aec3cd49b92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Bottom Navigation/Campus/Interactive Management/Class Circle/Class Training/class_training_change</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1b869a68-b123-4060-b5f2-8beba04a1b05</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Bottom Navigation/Campus/Interactive Management/Class Circle/Notice/notice_view_and_verify_text</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7ff655e-906d-4d90-b031-48998c360421</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bc5ae90-2be3-454b-a09d-8855fcc705bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1abeffb4-2699-491c-bac2-aaa314d22ff7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f3b439d-21df-4c2d-b3c0-8fcc5614003c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e363f2d9-5493-440f-8fee-f7166cdaa3be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Bottom Navigation/Campus/Interactive Management/Class Circle/Album/album_publish</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cbd3ae2-de12-4265-b0bd-0e345f245f52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a82fcf91-24e8-4eea-a06a-c2079cf5c2c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f410a983-2a91-477c-a365-8839ade75743</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6e69745-19dc-4bf4-82bf-1d7493db4a91</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
