<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>手机短信用例集合</description>
   <name>sms</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>21b6fc0d-74b5-493c-8336-c69d08957754</testSuiteGuid>
   <testCaseLink>
      <guid>45529d6d-00cf-4fc3-95b6-e20743aff3d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Bottom Navigation/Campus/Interactive Management/SMS/Sending SMS/send_sms_to_all_teacher</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d62a8d5e-7219-4b2d-a926-2131fd003109</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39fc2538-b57e-4fb9-80e8-fa75dc6827c4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
