<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>手机短信用例集合</description>
   <name>sms</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>21b6fc0d-74b5-493c-8336-c69d08957754</testSuiteGuid>
   <testCaseLink>
      <guid>45529d6d-00cf-4fc3-95b6-e20743aff3d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Bottom Navigation/Campus/Interactive Management/SMS/Sending SMS/send_sms_to_all_teacher</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d62a8d5e-7219-4b2d-a926-2131fd003109</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39fc2538-b57e-4fb9-80e8-fa75dc6827c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52f48a48-a0ea-476f-ab04-445d00174f94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Bottom Navigation/Campus/Interactive Management/SMS/Sending SMS/send_sms_and_no_concact</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ad2df4e-30fb-475d-a427-1b4fd6d2393f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b16ed6c-7920-4e5e-bec1-c10f44aee985</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Bottom Navigation/Campus/Interactive Management/SMS/Sending SMS/send_sms_to_all_student</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5cac5ae-4873-4dd1-8210-287b57ecfdb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1a139b2-88ed-4bb7-ab7a-4866bfc27a2c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
