<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>teacher</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>420ccc6c-d524-4268-a1ad-70812d39ab3c</testSuiteGuid>
   <testCaseLink>
      <guid>7a68cdcb-ef17-47ac-ae11-a0af3a5752c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IOS App/Choose City/choose_puning</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f06f3b1e-50c5-4a9b-b021-34ed90c0dbc7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8457d450-01ab-44b7-860c-b429fabc0722</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IOS App/Login And Page/login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b65507-d112-4b42-8bd3-d3fc335db871</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eec255f-284d-47f3-ba3d-d9192ae89e2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df713f3d-3f81-4f71-a197-c4877a109a8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IOS App/Teacher (1)/Headmaster/_Campus/_Interactive Management/tap_sms</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
